### ISSUE TITLE
Transitive closure is not computed for instances

### ISSUE THREAD

**Issue by DavidLeoni** [DavidLeoni/diversicon#32]
Currently transitive closure is computed only for transitive relations, one relation at a time. This means that in transitive relations like `hypernym` which have special relations for leaves  like `instanceHypernym`, the instances are not linked to the chain of parents. 

For our purposes, this may be particularly problematic for calculations regarding domains.

**Comment by gbella** [comment]
I think this behaviour is perfectly fine both scientifically and in
practice.

As long as we have the transitive closure on superdomains, the user can
always implement the check very easily:
if (synset hasDomain D) and (D hasSuperDomain SD) then...

**Comment by DavidLeoni** [comment]
Yes right, basically applications using Diversicon would need to be a little smarter and on Diversicon side we would save a lot of memory in extra edges, especially for entities. Closing this.
